# Gems
gems:
  - jekyll-paginate

# Site settings
title: Citazioni da libri e articoli | Andrea Zanni
email: aubreymcfato@gmail.com
url: "https://github.com/Aubreymcfato/highlights/tree/gh-pages/"
images: /assets/images/covers


# Blog settings
paginate: 10
paginate_path: "/all/page:num/"
permalink: /book/:title/

# Build settings
markdown: kramdown
theme: minima
sass:
  sass_dir: assets/_sass
  style: compressed
