# Gems
gems:
  - jekyll-paginate

# Site settings
title: Citazioni da libri e articoli | Andrea Zanni
email: aubreymcfato@gmail.com
url: "https://aubreymcfato.github.io/highlights/"
images: /highlights/assets/images/covers


# Blog settings
paginate: 10
paginate_path: "/highlights/all/page:num/"
permalink: /highlights/book/:title/

# Build settings
markdown: kramdown
theme: minima
sass:
  sass_dir: highlights/assets/_sass
  style: compressed
